version: "3.3"
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: "wishlist-nginx"
    volumes:
      - ./docker/log/nginx:/var/log/nginx
    environment:
      - VIRTUAL_HOST=wish.toutounode.localhost

networks:
  default:
    external:
      name: toutou_shared
